clone:
  depth: full
pipelines:
  default:
    - step:
        name: Build and Test
        image: node:14.16.1
        script:
          - yarn install
          - yarn run test
          - yarn run build
    - step:
        name: Lint
        image: node:14.16.1
        script:
          - yarn install
          - yarn run lint
  branches:
    master:
      - step:
          name: Build and Test
          image: node:14.16.1
          script:
            - yarn install
            - yarn run test
            - yarn run build
      - step:
          name: Lint
          image: node:14.16.1
          script:
            - yarn install
            - yarn run lint
      - step:
          name: Publish Prod
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/api-salty-sparkdigital.git HEAD:master -f
