### GET ROUNDS
GET http://localhost:3000/rounds

### GET ROUND BY ID
GET http://localhost:3000/rounds/ed6442f5-339a-4a02-b8a7-268396e3105a

### DELETE ROUND BY ID
DELETE http://localhost:3000/rounds/c0b794e6-9063-48e3-8a07-33c701s30d6e

### UPDATE ROUND
PUT http://localhost:3000/rounds/ed6442f5-339a-4a02-b8a7-268396e3105a
content-type: application/json

{
  "name": "Round 2"
}

### ADD ROUND
POST http://localhost:3000/rounds
content-type: application/json

{
  "createdBy": "5c9f8f8f-f912-4b4e-9016-4ef9c28bec06",
  "name": "Round 1",
  "startDate": "2022-01-11T00:00:00.000Z",
  "endDate": "2022-01-20T00:00:00.000Z",
  "comments": "The best round ever",
  "isActive": true
}