### GET USER-FRIENDS
GET http://localhost:3000/users/1341132/rounds/515984d4-cfde-4ddb-9203-fc4355590f23

### DELETE USER-FRIENDS BY ID
DELETE http://localhost:3000/users/1341132/rounds/515984d4-cfde-4ddb-9203-fc4355590f23

### UPDATE USER-FRIENDS
PUT http://localhost:3000/users/1341132/rounds/515984d4-cfde-4ddb-9203-fc4355590f23
content-type: application/json

{
  "giftPhoto": "",
  "giftDescription": "Ese es mi comentario 2",
  "giftDate": "2022-01-20T00:00:00.000Z",
  "hasGift": true
}

### ADD USER-FRIENDS
POST http://localhost:3000/users/1341132/rounds/515984d4-cfde-4ddb-9203-fc4355590f23